### ISSUE TITLE
Support multiple instances of AdGuardHome?

### ISSUE THREAD

**Issue by ryanelliottsmith** [muhlba91/external-dns-provider-adguard#103]
I run 2 AdGuardHome instances for redundancy, with config mirrored between them through a cronjob.
Looking through the documentation, I'm not sure if it's possible to support multiple AdGuardHome instances in this plugin, but that would be great if possible.

**Comment by muhlba91** [comment]
as you found out already you can only specify one instance of adguard in this plugin.

as a workaround, you can run a second instance of external-dns and this plugin to account for the second adguard instance though...

i'll see how such a feature could be added with keeping the current way to specify the configuration via environment variables.

**Comment by rouke-broersma** [comment]
@ryanelliottsmith I use adguard home sync to mirror my config between primary and readonly instances, this also sync's dns records so the records only need to be injected into the primary instance by the externaldns provider.
