### ISSUE TITLE
Allow configuring/specifying "important" rule modifier [Feature Request]

### ISSUE THREAD

**Issue by brianramseyau** [muhlba91/external-dns-provider-adguard#118]
Thank you for the provider, it has really come in handy as I have spun up a new home lab test environment and managing DNS records much like I do in my work systems with Cloudflare.

I would request a feature, and having looked through the configuration I do believe it would need to be added.

This would be enabling us to specify (even just a boolean) for the records to have the `important` modifier, which would just be appended to the end of the currently written string as `,important`. See more here: https://adguard-dns.io/kb/general/dns-filtering-syntax/#important-modifier and see here about using multiple at once https://adguard-dns.io/kb/general/dns-filtering-syntax/#rule-modifiers 

This would allow those of us who are writing to the same TLD, the ability to not need to actively monitor the rewrite rules.

I currently have the bulk of my traffic for my TLD wild-carded in rules as below:
`||domain.tld^$dnsrewrite=NOERROR;A;192.168.1.x`

The issue is, where another rule is written by the provider after this, such as:
`|subdomain.domain.tld^$dnsrewrite=NOERROR;A;192.168.1.x`

It gets appended onto the A record (results in returning multiple A records). This isn't a huge issue if the rules are in the correct order, however with this plugin I lose control of ordering and cannot keep my wildcard at the bottom to be added last, resulting in the wildcard serving the content instead (which doesn't exist).

Using `important` on the added rules would raise the priority of them above the wildcard rule I use, and then the order of rules wouldn't matter in this case.

**Comment by muhlba91** [comment]
i agree, adding this will be beneficial and thank you for pointing out the `important` modifier for it.

since it's just a single flag, i suggest adding a new environment variable to control this behaviour.

**Comment by muhlba91** [comment]
`v6.0.0` adds this flag by default.

after considerations i thought it makes sense to make it a default action due to the way adguard evaluates rules. users should explicitly need to turn it off.

**Comment by brianramseyau** [comment]
I have pulled this image down, and it's working exactly as detailed. Thanks so much, did not expect such a quick turn-around! :)
