### ISSUE TITLE
Possible Subdomain Handling Improvement

### ISSUE THREAD

**Issue by gabe565** [muhlba91/external-dns-provider-adguard#54]
Hi!

Thank you for this provider! It's been working great, but I was just looking through the AdGuard DNS docs, and I found a special character that may improve how subdomains are handled.

The [DNS filtering rules syntax](https://adguard-dns.io/kb/general/dns-filtering-syntax/#special-characters) doc mentions the pipe character, which does the following:
> `|`: a pointer to the beginning or the end of the hostname. The value depends on the character placement in the mask. For example, the rule `ample.org|` corresponds to `example.org` but not to `example.org.com`. `|example` corresponds to `example.org` but not to `test.example`.

This makes it sound like pipe won't work for this provider, but I did some testing and it seems to behave better than `||`. I added the following rule`|example.com^$dnsrewrite=NOERROR;A;192.168.1.1`, then I queried different domains:
```shell
❯ dig +short example.com
192.168.1.1
❯ dig +short example.comtest
❯ dig +short example.com.test
❯ dig +short test.example.com
❯ dig +short testexample.com
13.248.169.48
76.223.54.146
```

It seems like when a rule starts with `|`, it is still anchored at the end, but subdomains won't be matched like they are with `||`.

I also verified that record types other than `A` still work.

Do you think a single pipe would make more sense for this provider?

**Comment by muhlba91** [comment]
thank you for pointing it out! 👍 
i must have overlooked it back then as i was searching for a solution to this subdomain handling issue.

yes, it makes sense; if this works flawlessly, it solves that known problem. i'll have a go at it myself and integrate it if it works.

**Comment by muhlba91** [comment]
it looks good to me - i would plan to make a release chain:

1. release a new major version based on #55 (would you have a look at it?), which still accepts reading the old format and writes it using the new one
2. release another major version that removes backward compatibility

this way, automated updates of minor version releases do not jump directly to the last version, which would ignore the old records, and a clear upgrade path is provided for everyone. what do you think?

and yes, regarding your second point. if you have an idea of how the ownership can get fixed without issues, i'm happy to discuss it. 👍

**Comment by muhlba91** [comment]
both versions are now released - please follow the upgrade path `v4` and then `v5` once `v4` has reconciled...
i tested this on my clusters and all went smoothly on my side.

**Comment by gabe565** [comment]
This is great! I built my own container and was also testing with no issue. I'll go ahead and upgrade. Thank you!
